services:
  millinks_webapp:
    image: robsonnatanael/millinks:latest
    environment:
      - API_CLIENT_ID=${API_CLIENT_ID}
      - API_CLIENT_SECRET=${API_CLIENT_SECRET}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_API_AUTH_URL=${NEXT_PUBLIC_API_AUTH_URL}
      - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}

    networks:
      - traefik_traefik_proxy

    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure

      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.millinks_webapp.rule=Host(`tech.robsonnatanael.com.br`) && PathPrefix(`/millinks`)'
        - 'traefik.http.routers.millinks_webapp.entrypoints=websecure'
        - 'traefik.http.routers.millinks_webapp.tls=true'
        - 'traefik.http.services.millinks_webapp.loadbalancer.server.port=3000'

  millinks_docs:
    image: robsonnatanael/millinks-docs:latest

    networks:
      - traefik_traefik_proxy

    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure

      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.millinks-docs.rule=Host(`tech.robsonnatanael.com.br`) && PathPrefix(`/millinks-docs`)'
        - 'traefik.http.routers.millinks-docs.entrypoints=websecure'
        - 'traefik.http.routers.millinks-docs.tls=true'
        - 'traefik.http.services.millinks-docs.loadbalancer.server.port=80'

networks:
  traefik_traefik_proxy:
    external: true
