name: Releases

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '^22.12.0'

      - name: Install dependencies
        run: yarn install

      - name: Run release
        run: yarn release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
